apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: fastnext
data:
  DATABASE_URL: "postgresql+psycopg2://postgres:postgres@postgres:5432/mydb"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"